load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

exports_files([
    "go.mod",
    "go.sum",
])

go_library(
    name = "parser",
    srcs = [
        "digester.go",
        "hint_token_kinds.go",
        "hintparserimpl.go",
        "keyword_classes.go",
        "keywords.go",
        "lexer.go",
        "misc.go",
        "parse_admin.go",
        "parse_alter.go",
        "parse_analyze.go",
        "parse_binding.go",
        "parse_brie.go",
        "parse_column.go",
        "parse_create_index.go",
        "parse_create_misc.go",
        "parse_create_table.go",
        "parse_create_view.go",
        "parse_dml.go",
        "parse_drop.go",
        "parse_expr.go",
        "parse_flashback.go",
        "parse_func.go",
        "parse_grant.go",
        "parse_hint.go",
        "parse_misc.go",
        "parse_procedure.go",
        "parse_rename.go",
        "parse_select.go",
        "parse_set.go",
        "parse_show.go",
        "parse_tidb.go",
        "parse_txn.go",
        "parse_types.go",
        "rd_errors.go",
        "rd_parser.go",
        "redact.go",
        "token_kinds.go",
        "yy_parser.go",
    ],
    importpath = "github.com/sqlc-dev/marino/parser",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/parser/ast",
        "//pkg/parser/auth",
        "//pkg/parser/charset",
        "//pkg/parser/duration",
        "//pkg/parser/mysql",
        "//pkg/parser/opcode",
        "//pkg/parser/terror",
        "//pkg/parser/tidb",
        "//pkg/parser/types",
        "//pkg/parser/util",
        "@com_github_pingcap_errors//:errors",
    ],
)

go_test(
    name = "parser_test",
    timeout = "short",
    srcs = [
        "bench_test.go",
        "consistent_test.go",
        "digester_test.go",
        "hintparser_test.go",
        "keywords_test.go",
        "lateral_test.go",
        "lexer_test.go",
        "main_test.go",
        "parser_test.go",
        "rd_errors_test.go",
    ],
    data = glob(["**"]),
    embed = [":parser"],
    flaky = True,
    shard_count = 50,
    deps = [
        "//pkg/parser/ast",
        "//pkg/parser/charset",
        "//pkg/parser/format",
        "//pkg/parser/mysql",
        "//pkg/parser/opcode",
        "//pkg/parser/terror",
        "@com_github_pingcap_errors//:errors",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_goleak//:goleak",
    ],
)
