// Copyright 2026 The sqlc Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

package parser

// Error-fidelity corpus: every invalid input the pre-rewrite test suite
// exercised, with the goyacc parser's exact error and warning strings
// recorded before its removal. The parser must reproduce them
// byte-for-byte.

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

// Fields are []byte so invalid-UTF-8 inputs survive the JSON round trip
// (base64), which string fields silently corrupt to U+FFFD.
type errCorpusEntry struct {
	SQL   []byte   `json:"sql"`
	Err   []byte   `json:"err"`
	Warns [][]byte `json:"warns,omitempty"`
}

const errCorpusPath = "testdata/errors.json"

// The corpus was generated by the goyacc oracle before its removal; to
// regenerate, check out the last commit containing parser/parser.y and
// run the recipe above from there.

// TestRDErrorFidelity checks the RD parser's error mode against the
// recorded corpus.
func TestRDErrorFidelity(t *testing.T) {
	data, err := os.ReadFile(errCorpusPath)
	if err != nil {
		t.Skip("no error corpus present")
	}
	mismatches := 0
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	sc.Buffer(make([]byte, 1024*1024), 1024*1024)
	for sc.Scan() {
		var e errCorpusEntry
		if err := json.Unmarshal(sc.Bytes(), &e); err != nil {
			t.Fatal(err)
		}
		sql := string(e.SQL)
		p := New()
		resetParams(p)
		p.lexer.reset(sql)
		CharsetConnection("").ApplyOn(p)
		CollationConnection("").ApplyOn(p)
		p.src = sql
		_, warns, perr := p.parseRD(sql)
		report := func(format string, args ...interface{}) {
			mismatches++
			if mismatches <= 20 {
				t.Errorf("SQL: %s\n  %s", sql, fmt.Sprintf(format, args...))
			}
		}
		if perr == nil {
			report("rd accepted; yacc error: %s", e.Err)
			continue
		}
		if perr.Error() != string(e.Err) {
			report("error mismatch\n  rd  : %s\n  yacc: %s", perr.Error(), e.Err)
			continue
		}
		var gotWarns []string
		for _, w := range warns {
			gotWarns = append(gotWarns, w.Error())
		}
		if len(gotWarns) != len(e.Warns) {
			report("warn count mismatch rd=%v yacc=%v", gotWarns, e.Warns)
			continue
		}
		for i := range gotWarns {
			if gotWarns[i] != string(e.Warns[i]) {
				report("warn mismatch\n  rd  : %s\n  yacc: %s", gotWarns[i], e.Warns[i])
				break
			}
		}
	}
	if mismatches > 20 {
		t.Errorf("... and %d more mismatches", mismatches-20)
	}
	if mismatches > 0 {
		t.Logf("total mismatches: %d", mismatches)
	}
}
